import React from 'react'

function Samples() {
  return (
    <div class="dark:bg-gradient-to-r from-start to-end font-[sans-serif] bg-gray-100 px-4 py-12 pb-20">
      <div class="max-w-5xl max-lg:max-w-3xl mx-auto">
        <div class="text-center">
          <h2 class="text-3xl font-bold mb-3 dark:text-white text-gray-800">Sample Books Generated by BookAI</h2>
          <p class="dark:text-gray-200 text-lg text-gray-500">Explore some of the captivating books created using our AI technology</p>
        </div>

        <div class="grid lg:grid-cols-3 sm:grid-cols-1 gap-12 max-sm:max-w-sm max-sm:mx-auto mt-12">

          <div class="dark:bg-secondary flex flex-col justify-center items-center bg-white shadow rounded-2xl p-4 hover:-translate-y-3 transition-all duration-300">
            <div className='w-48 mb-4'>
              <img src={require('../assets/sample1.jpeg')} alt="sample-1"/>
            </div>
            <div className='flex items-center flex-col'>
            <h4 class="dark:text-white text-gray-800 font-bold text-lg">Science Fiction</h4>
            <p className='text-center dark:text-gray-400 font-md mb-2'>"As Dr. Elara stepped through the shimmering portal, she knew there was no turning back. The fate of two universes now rested in her hands..."</p>
            <p className='cursor-pointer text-center dark:hover:text-white transition-all duration-300 dark:text-purple-700 font-md'>Read More</p>
            </div>
          </div>

          <div class="dark:bg-secondary flex flex-col justify-center items-center bg-white shadow rounded-2xl p-4 hover:-translate-y-3 transition-all duration-300">
            <div className='w-48 mb-4'>
              <img src={require('../assets/sample2.jpeg')} alt="sample-1"/>
            </div>
            <div className='flex items-center flex-col'>
            <h4 class="dark:text-white text-gray-800 font-bold text-lg">Mystery</h4>
            <p className='text-center dark:text-gray-400 font-md mb-2'>"The old lighthouse stood silent, its beacon long extinguished. But on foggy nights, some swore they could still see its ghostly light..."</p>
            <p className='cursor-pointer text-center dark:hover:text-white transition-all duration-300 dark:text-purple-700 font-md'>Read More</p>
            </div>
          </div>

          <div class="dark:bg-secondary flex flex-col justify-center items-center bg-white shadow rounded-2xl p-4 hover:-translate-y-3 transition-all duration-300">
            <div className='w-48 mb-4'>
              <img src={require('../assets/sample3.jpeg')} alt="sample-1"/>
            </div>
            <div className='flex items-center flex-col'>
            <h4 class="dark:text-white text-gray-800 font-bold text-lg">Fantasy</h4>
            <p className='text-center dark:text-gray-400 font-md mb-2'>"The ancient prophecy spoke of a child born with starlight in their eyes. As the comet blazed overhead, the kingdom held its breath..."</p>
            <p className='cursor-pointer text-center dark:hover:text-white transition-all duration-300 dark:text-purple-700 font-md'>Read More</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

export default Samples